<?php
/**
 * Plugin Name: Gogh Editor
 * Description: A freeform canvas for WordPress — drag anything anywhere on your live page; Gogh publishes it back as clean, responsive core blocks that keep working even if the plugin is deactivated.
 * Version: 0.99.60
 * Author: Jamie Marsland
 * Author URI: https://pootlepress.com
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Requires at least: 6.5
 * Requires PHP: 7.4
 * Text Domain: gogh-editor
 */

defined( 'ABSPATH' ) || exit;

/**
 * gogh/section — a first-class block. STATIC save (no render_callback), so
 * pages keep rendering identically if the plugin is ever deactivated.
 */
add_action( 'init', function () {
	wp_register_script(
		'gogh-block',
		plugins_url( 'gogh-block.js', __FILE__ ),
		array( 'wp-blocks', 'wp-element', 'wp-block-editor' ),
		'0.99.60-chrome',
		true
	);
	register_block_type( 'gogh/section', array(
		'editor_script'   => 'gogh-block',
		// SPIKE (attrs-as-truth): v3 sections store { model, cssT } as block
		// attributes and derive presentation here. Legacy (v2) sections carry
		// no attributes and pass through verbatim — fully static, unchanged.
		'render_callback' => 'gogh_render_section',
	) );
} );

/**
 * SPIKE: emit a v3 section. PHP does scoping + emission ONLY — the layout
 * engine stays in the editor; cssT arrives fully compiled with a GOGHSCOPE
 * placeholder.
 *
 * SECURITY: block attributes are writable by users WITHOUT unfiltered_html
 * (KSES does not police attribute JSON), so everything emitted from them is
 * sanitized here: the scope is slug-cast and the CSS may not contain the
 * characters that could open an element or comment. Without this, cssT would
 * be a stored-XSS bypass around KSES.
 */
function gogh_css_from_attrs( $attrs ) {
	if ( empty( $attrs['cssT'] ) || empty( $attrs['scope'] ) ) {
		return '';
	}
	$scope = preg_replace( '/[^a-z0-9-]/', '', (string) $attrs['scope'] );
	if ( '' === $scope ) {
		return '';
	}
	$css = str_replace( 'GOGHSCOPE', $scope, (string) $attrs['cssT'] );
	// CSS never needs these characters; their absence makes markup injection impossible
	return str_replace( array( '<', '>', '\\' ), '', $css );
}

/**
 * When KSES strips a baked <style> TAG it leaves the CSS behind as loose
 * text. Our stylesheets all open with a sentinel comment and never contain
 * '<', so the residue is precisely delimited and safe to sweep.
 */
function gogh_sweep_css_residue( $html ) {
	return preg_replace( '/\/\* generated by gogh \*\/[^<]*/', '', $html );
}

function gogh_render_section( $attrs, $content ) {
	$attrs = is_array( $attrs ) ? $attrs : array();
	$css   = gogh_css_from_attrs( $attrs );
	if ( '' === $css ) {
		return $content; // legacy v2: static markup is already complete
	}
	if ( false === strpos( $content, 'class="gogh-style"' ) ) {
		$content = gogh_sweep_css_residue( $content );
		$style   = '<style class="gogh-style">' . $css . '</style>';
		$out     = preg_replace( '/(<div class="wp-block-gogh-section[^"]*">)/', '$1' . $style, $content, 1, $n );
		$content = $n ? $out : $style . $content;
	}
	return gogh_inject_experiences( $attrs, gogh_faq_schema( $attrs ) . $content );
}

/**
 * FAQ sections carry their questions as DATA in the model — so the render
 * can speak schema.org fluently: one FAQPage JSON-LD script per FAQ
 * section, generated fresh on every render (never stored, never kses'd).
 */
function gogh_faq_schema( $attrs ) {
	$els = isset( $attrs['model']['elements'] ) && is_array( $attrs['model']['elements'] )
		? $attrs['model']['elements'] : array();
	$qa = array();
	foreach ( $els as $e ) {
		if ( empty( $e['faq'] ) || ! is_array( $e['faq'] ) ) {
			continue;
		}
		foreach ( $e['faq'] as $item ) {
			if ( empty( $item['q'] ) || empty( $item['a'] ) ) {
				continue;
			}
			$qa[] = array(
				'@type'          => 'Question',
				'name'           => wp_strip_all_tags( $item['q'] ),
				'acceptedAnswer' => array(
					'@type' => 'Answer',
					'text'  => wp_strip_all_tags( $item['a'] ),
				),
			);
		}
	}
	if ( ! $qa ) {
		return '';
	}
	$schema = array(
		'@context'   => 'https://schema.org',
		'@type'      => 'FAQPage',
		'mainEntity' => $qa,
	);
	return '<script type="application/ld+json">' . wp_json_encode( $schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . '</script>';
}

/**
 * Experiences: stored markup carries only a plain link (kses-safe, and the
 * plugin-off fallback). At render time it becomes a sandboxed iframe. The
 * src is NEVER taken from attributes — only the attachment ID is, and the
 * URL is resolved server-side after checking the attachment really is an
 * uploaded text/html file (uploads of which are capability-gated below).
 * allow-scripts WITHOUT allow-same-origin = opaque origin: the uploaded
 * code cannot read cookies or reach the embedding page.
 */
function gogh_inject_experiences( $attrs, $content ) {
	$els = isset( $attrs['model']['elements'] ) && is_array( $attrs['model']['elements'] )
		? $attrs['model']['elements'] : array();
	foreach ( $els as $i => $e ) {
		if ( empty( $e['type'] ) || 'exp' !== $e['type'] || empty( $e['expId'] ) ) {
			continue;
		}
		$id = intval( $e['expId'] );
		if ( $id <= 0 || 'text/html' !== get_post_mime_type( $id ) ) {
			continue;
		}
		$src = wp_get_attachment_url( $id );
		if ( ! $src ) {
			continue;
		}
		$iframe  = '<iframe src="' . esc_url( $src ) . '" sandbox="allow-scripts" title="Interactive experience" loading="lazy" style="width:100%;height:100%;border:0;display:block"></iframe>';
		// the class list gains render-time extras (layout support), so match
		// by our two authored classes rather than the exact attribute value
		$content = preg_replace_callback(
			'/(<div class="[^"]*\bgogh-el-' . ( $i + 1 ) . '\b[^"]*\bgogh-exp\b[^"]*">).*?<\/div>/s',
			function ( $m ) use ( $iframe ) {
				return $m[1] . $iframe . '</div>';
			},
			$content,
			1
		);
	}
	return $content;
}

/**
 * Page styles: a gogh-provided "Blank canvas" template — post content only,
 * no site header or footer. Registered as a plugin block template (WP 6.7+);
 * on older WordPress the option simply doesn't appear.
 */
add_action( 'init', function () {
	if ( ! function_exists( 'register_block_template' ) ) {
		return;
	}
	register_block_template( 'gogh//blank-canvas', array(
		'title'       => __( 'Blank canvas', 'gogh-editor' ),
		'description' => __( 'Just your content, no site header or footer.', 'gogh-editor' ),
		'post_types'  => array( 'page' ),
		'content'     => '<!-- wp:group {"tagName":"main","layout":{"type":"default"},"style":{"spacing":{"blockGap":"0","margin":{"top":"0","bottom":"0"}}}} --><main class="wp-block-group" style="margin-top:0;margin-bottom:0"><!-- wp:post-content /--></main><!-- /wp:group -->',
	) );
} );

/**
 * Gogh's own patterns: a few pattern-directory favourites captured as plugin
 * patterns (they aren't registered locally by any theme), so every theme gets
 * a decent shelf in the section picker.
 */
add_action( 'init', function () {
	$pats = array(
		'fullscreen-cover-image-gallery' => array( __( 'Fullscreen cover image gallery', 'gogh-editor' ), array( 'gallery', 'banner' ) ),
		'fullwidth-headline-right'       => array( __( 'Fullwidth headline and description', 'gogh-editor' ), array( 'banner' ) ),
		'simple-call-to-action'          => array( __( 'Simple call to action', 'gogh-editor' ), array( 'call-to-action' ) ),
		'three-column-pricing-table'     => array( __( 'Three column pricing table', 'gogh-editor' ), array( 'call-to-action' ) ),
	);
	foreach ( $pats as $slug => $info ) {
		$file = __DIR__ . '/patterns/' . $slug . '.html';
		if ( ! is_readable( $file ) ) {
			continue;
		}
		register_block_pattern( 'gogh/' . $slug, array(
			'title'      => $info[0],
			'categories' => $info[1],
			'content'    => file_get_contents( $file ),
		) );
	}

	// gogh's own headers and footers: a curated shelf for the Change
	// header/footer flicker, so every site gets good choices regardless of
	// what the theme ships. Built from core blocks with theme preset
	// colours — they re-dress when the site style changes.
	$chrome = array(
		'gogh-header-classic' => array( __( 'Classic header — logo left, menu right', 'gogh-editor' ), 'header' ),
		'gogh-header-centred' => array( __( 'Centred header — stacked and calm', 'gogh-editor' ), 'header' ),
		'gogh-header-minimal' => array( __( 'Minimal header — one quiet line', 'gogh-editor' ), 'header' ),
		'gogh-header-bold'    => array( __( 'Bold header — a solid band', 'gogh-editor' ), 'header' ),
		'gogh-header-split'   => array( __( 'Split header — menu centred, search right', 'gogh-editor' ), 'header' ),
		'gogh-header-overlay' => array( __( 'Transparent header — floats over your hero', 'gogh-editor' ), 'header' ),
		'gogh-footer-simple'  => array( __( 'Simple footer — everything centred', 'gogh-editor' ), 'footer' ),
		'gogh-footer-columns' => array( __( 'Columns footer — brand, menu, small print', 'gogh-editor' ), 'footer' ),
		'gogh-footer-bold'    => array( __( 'Bold footer — a solid band', 'gogh-editor' ), 'footer' ),
	);
	foreach ( $chrome as $slug => $info ) {
		$file = __DIR__ . '/patterns/' . $slug . '.html';
		if ( ! is_readable( $file ) ) {
			continue;
		}
		register_block_pattern( 'gogh/' . $slug, array(
			'title'       => $info[0],
			'categories'  => array( $info[1] ),
			'blockTypes'  => array( 'core/template-part/' . $info[1] ),
			'viewportWidth' => 1200,
			'content'     => file_get_contents( $file ),
		) );
	}
} );

/**
 * Starter sites: whole sites (pages + menu + front page) shipped as
 * manifests + block-markup files under starters/<slug>/. Pages register as
 * hidden patterns so the preview route can render them; applying a starter
 * is one REST call that trashes current pages (restorable), creates the new
 * set, rebuilds the menu, and wires the front and posts pages.
 */
function gogh_starters() {
	$out = array();
	foreach ( glob( __DIR__ . '/starters/*/manifest.json' ) as $mf ) {
		$slug = basename( dirname( $mf ) );
		$m    = json_decode( file_get_contents( $mf ), true );
		if ( $m && ! empty( $m['pages'] ) ) {
			$m['slug']    = $slug;
			$out[ $slug ] = $m;
		}
	}
	return $out;
}
function gogh_starter_page_content( $slug, $pg ) {
	$file = __DIR__ . '/starters/' . $slug . '/' . basename( $pg['file'] );
	if ( ! is_readable( $file ) ) {
		return '';
	}
	return str_replace(
		array( '{{gogh_theme}}', '{{gogh_plugin}}' ),
		array( get_template_directory_uri(), untrailingslashit( plugins_url( '', __FILE__ ) ) ),
		file_get_contents( $file )
	);
}
add_action( 'init', function () {
	foreach ( gogh_starters() as $slug => $m ) {
		foreach ( $m['pages'] as $pg ) {
			$content = gogh_starter_page_content( $slug, $pg );
			if ( '' === $content ) {
				continue;
			}
			register_block_pattern( 'gogh-starter/' . $slug . '-' . $pg['slug'], array(
				'title'    => $m['name'] . ' — ' . $pg['title'],
				'inserter' => false,
				'content'  => $content,
			) );
		}
	}
} );
add_action( 'rest_api_init', function () {
	register_rest_route( 'gogh/v1', '/starter', array(
		'methods'             => 'POST',
		'permission_callback' => function () {
			return current_user_can( 'manage_options' );
		},
		'args'                => array( 'slug' => array( 'required' => true, 'type' => 'string' ) ),
		'callback'            => function ( $req ) {
			$starters = gogh_starters();
			$slug     = sanitize_key( $req['slug'] );
			if ( empty( $starters[ $slug ] ) ) {
				return new WP_Error( 'gogh_no_starter', __( 'Unknown site design.', 'gogh-editor' ), array( 'status' => 404 ) );
			}
			$m = $starters[ $slug ];
			// current pages step aside, restorably — never deleted
			$old = get_posts( array(
				'post_type'   => 'page',
				'post_status' => array( 'publish', 'draft', 'private', 'pending' ),
				'numberposts' => -1,
				'fields'      => 'ids',
			) );
			foreach ( $old as $oid ) {
				wp_trash_post( $oid );
			}
			$front = 0;
			$blog  = 0;
			$made  = array();
			foreach ( $m['pages'] as $pg ) {
				$id = wp_insert_post( array(
					'post_type'    => 'page',
					'post_status'  => 'publish',
					'post_title'   => $pg['title'],
					'post_name'    => $pg['slug'],
					'post_content' => gogh_starter_page_content( $slug, $pg ),
					'meta_input'   => empty( $pg['template'] ) ? array()
						: array( '_wp_page_template' => sanitize_key( $pg['template'] ) ),
				) );
				if ( ! $id || is_wp_error( $id ) ) {
					continue;
				}
				$made[] = array(
					'id'      => $id,
					'title'   => $pg['title'],
					'no_menu' => isset( $pg['menu'] ) && false === $pg['menu'],
				);
				if ( ! empty( $pg['front'] ) ) {
					$front = $id;
				}
				if ( ! empty( $pg['blog'] ) ) {
					$blog = $id;
				}
			}
			if ( ! $made ) {
				return new WP_Error( 'gogh_starter_failed', __( 'The site design could not be applied.', 'gogh-editor' ), array( 'status' => 500 ) );
			}
			$links = '';
			foreach ( $made as $c ) {
				if ( ! empty( $c['no_menu'] ) ) {
					continue;
				}
				$links .= '<!-- wp:navigation-link {"label":"' . esc_attr( $c['title'] ) . '","type":"page","id":' . $c['id'] .
					',"url":"' . esc_url( get_permalink( $c['id'] ) ) . '","kind":"post-type"} /-->';
			}
			$nav_id = wp_insert_post( array(
				'post_type'    => 'wp_navigation',
				'post_status'  => 'publish',
				'post_title'   => $m['name'] . ' menu',
				'post_content' => $links,
			) );
			// point the live header's menu at the new navigation
			$part = get_block_template( get_stylesheet() . '//header', 'wp_template_part' );
			if ( $part && $nav_id && ! is_wp_error( $nav_id ) ) {
				$praw = (string) $part->content;
				$next = '';
				if ( preg_match( '/wp:navigation[^>]*"ref":\d+/', $praw ) ) {
					$next = preg_replace( '/("ref":)\d+/', '${1}' . $nav_id, $praw, 1 );
				} elseif ( preg_match( '/<!--\s+wp:navigation\s+\{/', $praw ) ) {
					$next = preg_replace( '/(<!--\s+wp:navigation\s+\{)/', '${1}"ref":' . $nav_id . ',', $praw, 1 );
				} else {
					$next = preg_replace( '/(<!--\s+wp:navigation)(\s+-->)/', '${1} {"ref":' . $nav_id . '}${2}', $praw, 1 );
				}
				if ( $next && $next !== $praw ) {
					if ( ! empty( $part->wp_id ) ) {
						wp_update_post( array( 'ID' => $part->wp_id, 'post_content' => $next ) );
					} else {
						$pid = wp_insert_post( array(
							'post_type'    => 'wp_template_part',
							'post_status'  => 'publish',
							'post_title'   => 'header',
							'post_name'    => 'header',
							'post_content' => $next,
						) );
						if ( $pid && ! is_wp_error( $pid ) ) {
							wp_set_post_terms( $pid, array( get_stylesheet() ), 'wp_theme' );
							wp_set_post_terms( $pid, array( 'header' ), 'wp_template_part_area' );
						}
					}
				}
			}
			// a starter may carry a bespoke PALETTE: theme palette slugs are
			// re-coloured (base/contrast keep roles, accents cycle), applied
			// as user global styles — same mechanism as Your brand
			if ( ! empty( $m['palette'] ) && class_exists( 'WP_Theme_JSON_Resolver' ) ) {
				$theme_pal = wp_get_global_settings( array( 'color', 'palette', 'theme' ) );
				if ( is_array( $theme_pal ) && $theme_pal ) {
					$pal     = $m['palette'];
					$accents = isset( $pal['accents'] ) && is_array( $pal['accents'] ) ? array_values( $pal['accents'] ) : array();
					$ai      = 0;
					$out_pal = array();
					foreach ( $theme_pal as $entry ) {
						$slug = isset( $entry['slug'] ) ? $entry['slug'] : '';
						if ( ( 'base' === $slug || 'background' === $slug ) && ! empty( $pal['base'] ) ) {
							$entry['color'] = $pal['base'];
						} elseif ( ( 'contrast' === $slug || 'text' === $slug || 'foreground' === $slug ) && ! empty( $pal['contrast'] ) ) {
							$entry['color'] = $pal['contrast'];
						} elseif ( $accents && 0 === strpos( $slug, 'accent' ) ) {
							$entry['color'] = $accents[ $ai % count( $accents ) ];
							$ai++;
						}
						$out_pal[] = $entry;
					}
					$gs_id = WP_Theme_JSON_Resolver::get_user_global_styles_post_id();
					if ( $gs_id ) {
						wp_update_post( array(
							'ID'           => $gs_id,
							'post_content' => wp_json_encode( array(
								'version'                     => class_exists( 'WP_Theme_JSON' ) ? WP_Theme_JSON::LATEST_SCHEMA : 3,
								'isGlobalStylesUserThemeJSON' => true,
								'settings'                    => array( 'color' => array( 'palette' => array( 'theme' => $out_pal ) ) ),
								'styles'                      => new stdClass(),
							) ),
						) );
					}
				}
			}
			// the design brings its own look: apply the named theme style
			// variation to user global styles. The user's saved gogh brand is
			// untouched and can be re-applied from Your brand at any time.
			if ( ! empty( $m['variation'] ) && class_exists( 'WP_Theme_JSON_Resolver' ) ) {
				foreach ( WP_Theme_JSON_Resolver::get_style_variations() as $v ) {
					if ( isset( $v['title'] ) && 0 === strcasecmp( $v['title'], $m['variation'] ) ) {
						$gs_id = WP_Theme_JSON_Resolver::get_user_global_styles_post_id();
						if ( $gs_id ) {
							wp_update_post( array(
								'ID'           => $gs_id,
								'post_content' => wp_json_encode( array(
									'version'                     => class_exists( 'WP_Theme_JSON' ) ? WP_Theme_JSON::LATEST_SCHEMA : 3,
									'isGlobalStylesUserThemeJSON' => true,
									'settings'                    => isset( $v['settings'] ) ? $v['settings'] : new stdClass(),
									'styles'                      => isset( $v['styles'] ) ? $v['styles'] : new stdClass(),
								) ),
							) );
						}
						break;
					}
				}
			}
			// remember which style the site now wears — WP itself forgets the
			// variation's name the moment it's copied into user global styles
			update_option( 'gogh_active_style', ! empty( $m['variation'] ) ? $m['variation'] : '' );
			update_option( 'show_on_front', 'page' );
			update_option( 'page_on_front', $front ? $front : $made[0]['id'] );
			update_option( 'page_for_posts', $blog ? $blog : 0 );
			return array( 'home' => get_permalink( $front ? $front : $made[0]['id'] ) );
		},
	) );

	register_rest_route( 'gogh/v1', '/type-scale', array(
		'methods'             => 'POST',
		'permission_callback' => function () {
			return current_user_can( 'edit_theme_options' );
		},
		'args'                => array( 'scale' => array( 'required' => true, 'type' => 'number' ) ),
		'callback'            => function ( $req ) {
			$scale = max( 80, min( 140, (int) $req['scale'] ) );
			update_option( 'gogh_type_scale', $scale );
			return array( 'scale' => $scale );
		},
	) );

	register_rest_route( 'gogh/v1', '/active-style', array(
		'methods'             => 'POST',
		'permission_callback' => function () {
			return current_user_can( 'edit_theme_options' );
		},
		'args'                => array( 'name' => array( 'required' => true, 'type' => 'string' ) ),
		'callback'            => function ( $req ) {
			$name = sanitize_text_field( $req['name'] );
			update_option( 'gogh_active_style', $name );
			return array( 'name' => $name );
		},
	) );

	// products live outside wp/v2 — gogh's own save route speaks the same
	// minimal contract the editor already uses (GET raw, POST content,
	// autosaves), registered under wp/v2 so the editor's root-splitting
	// URL arithmetic keeps working
	$gogh_product_perm = function ( $req ) {
		return current_user_can( 'edit_post', (int) $req['id'] );
	};
	$gogh_product_get = function ( $req ) {
		$p = get_post( (int) $req['id'] );
		if ( ! $p || 'product' !== $p->post_type ) {
			return new WP_Error( 'gogh_no_product', 'Not a product', array( 'status' => 404 ) );
		}
		return array( 'id' => $p->ID, 'content' => array( 'raw' => $p->post_content ) );
	};
	register_rest_route( 'wp/v2', '/gogh-product/(?P<id>\d+)', array(
		array(
			'methods'             => 'GET',
			'permission_callback' => $gogh_product_perm,
			'callback'            => $gogh_product_get,
		),
		array(
			'methods'             => 'POST',
			'permission_callback' => $gogh_product_perm,
			'callback'            => function ( $req ) use ( $gogh_product_get ) {
				$id = (int) $req['id'];
				$p  = get_post( $id );
				if ( ! $p || 'product' !== $p->post_type ) {
					return new WP_Error( 'gogh_no_product', 'Not a product', array( 'status' => 404 ) );
				}
				wp_update_post( array( 'ID' => $id, 'post_content' => (string) $req['content'] ) );
				return $gogh_product_get( $req );
			},
		),
	) );
	register_rest_route( 'wp/v2', '/gogh-product/(?P<id>\d+)/autosaves', array(
		'methods'             => 'POST',
		'permission_callback' => $gogh_product_perm,
		'callback'            => function ( $req ) {
			$id = (int) $req['id'];
			$p  = get_post( $id );
			if ( ! $p || 'product' !== $p->post_type ) {
				return new WP_Error( 'gogh_no_product', 'Not a product', array( 'status' => 404 ) );
			}
			if ( ! function_exists( 'wp_create_post_autosave' ) ) {
				require_once ABSPATH . 'wp-admin/includes/post.php';
			}
			$aid = wp_create_post_autosave( array(
				'post_ID'      => $id,
				'post_content' => (string) $req['content'],
				'post_title'   => $p->post_title,
				'post_type'    => 'product',
			) );
			return array( 'id' => is_wp_error( $aid ) ? 0 : (int) $aid );
		},
	) );
} );

/**
 * Product layouts: a FEW fixed, opinionated templates to pick from — never
 * a template editor. Classic is WooCommerce's own untouched template; the
 * gogh layouts add a content canvas below the buy box. Picking happens in
 * the admin bar, one click, per product.
 */
function gogh_product_layouts() {
	return array(
		''                     => __( 'Classic — WooCommerce\'s own', 'gogh-editor' ),
		'gogh-product-story'   => __( 'Story — buy box, then your sections', 'gogh-editor' ),
		'gogh-product-showcase' => __( 'Showcase — image-led and centred', 'gogh-editor' ),
	);
}
add_action( 'init', function () {
	if ( ! function_exists( 'register_block_template' ) || ! class_exists( 'WooCommerce' ) ) {
		return;
	}
	register_block_template( 'gogh//gogh-product-showcase', array(
		'title'       => __( 'Product showcase (gogh)', 'gogh-editor' ),
		'description' => __( 'Image first, everything centred; your sections below.', 'gogh-editor' ),
		'post_types'  => array( 'product' ),
		'content'     => '<!-- wp:template-part {"slug":"header"} /-->' .
			'<!-- wp:group {"tagName":"main","layout":{"inherit":true,"type":"constrained"},"style":{"spacing":{"blockGap":"0","margin":{"top":"0","bottom":"0"}}}} -->' .
			'<main class="wp-block-group" style="margin-top:0;margin-bottom:0">' .
			'<!-- wp:woocommerce/store-notices /-->' .
			'<!-- wp:group {"layout":{"type":"constrained","contentSize":"760px"},"style":{"spacing":{"padding":{"top":"2.5rem","bottom":"2.5rem"},"blockGap":"1rem"}}} --><div class="wp-block-group" style="padding-top:2.5rem;padding-bottom:2.5rem">' .
			'<!-- wp:woocommerce/product-image-gallery /-->' .
			'<!-- wp:post-title {"level":1,"textAlign":"center","__woocommerceNamespace":"woocommerce/product-query/product-title"} /-->' .
			'<!-- wp:group {"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} --><div class="wp-block-group">' .
			'<!-- wp:woocommerce/product-price {"isDescendentOfSingleProductTemplate":true,"textAlign":"center","fontSize":"large"} /-->' .
			'<!-- wp:woocommerce/add-to-cart-form /-->' .
			'</div><!-- /wp:group -->' .
			'</div><!-- /wp:group -->' .
			'<!-- wp:post-content /-->' .
			'</main><!-- /wp:group -->' .
			'<!-- wp:template-part {"slug":"footer"} /-->',
	) );
	register_block_template( 'gogh//gogh-product-story', array(
		'title'       => __( 'Product story (gogh)', 'gogh-editor' ),
		'description' => __( 'Woo sells up top; gogh tells the story below.', 'gogh-editor' ),
		'post_types'  => array( 'product' ),
		'content'     => '<!-- wp:template-part {"slug":"header"} /-->' .
			'<!-- wp:group {"tagName":"main","layout":{"inherit":true,"type":"constrained"},"style":{"spacing":{"blockGap":"0","margin":{"top":"0","bottom":"0"}}}} -->' .
			'<main class="wp-block-group" style="margin-top:0;margin-bottom:0">' .
			'<!-- wp:woocommerce/store-notices /-->' .
			'<!-- wp:group {"layout":{"type":"constrained"},"style":{"spacing":{"padding":{"top":"2rem","bottom":"2rem"}}}} --><div class="wp-block-group" style="padding-top:2rem;padding-bottom:2rem">' .
			'<!-- wp:columns {"align":"wide"} --><div class="wp-block-columns alignwide">' .
			'<!-- wp:column {"width":"45%"} --><div class="wp-block-column" style="flex-basis:45%"><!-- wp:woocommerce/product-image-gallery /--></div><!-- /wp:column -->' .
			'<!-- wp:column {"width":"55%"} --><div class="wp-block-column" style="flex-basis:55%">' .
			'<!-- wp:post-title {"level":1,"__woocommerceNamespace":"woocommerce/product-query/product-title"} /-->' .
			'<!-- wp:woocommerce/product-price {"isDescendentOfSingleProductTemplate":true,"fontSize":"large"} /-->' .
			'<!-- wp:woocommerce/add-to-cart-form /-->' .
			'</div><!-- /wp:column -->' .
			'</div><!-- /wp:columns -->' .
			'</div><!-- /wp:group -->' .
			'<!-- wp:post-content /-->' .
			'</main><!-- /wp:group -->' .
			'<!-- wp:template-part {"slug":"footer"} /-->',
	) );
} );

add_action( 'admin_post_gogh_product_layout_all', function () {
	$id = isset( $_GET['id'] ) ? (int) $_GET['id'] : 0;
	if ( ! current_user_can( 'edit_others_posts' ) ) {
		wp_die( esc_html__( 'You cannot change other products.', 'gogh-editor' ) );
	}
	check_admin_referer( 'gogh_product_layout_all' );
	$layout = $id ? get_page_template_slug( $id ) : '';
	if ( ! array_key_exists( $layout, gogh_product_layouts() ) ) {
		$layout = '';
	}
	$ids = get_posts( array(
		'post_type'      => 'product',
		'post_status'    => 'any',
		'posts_per_page' => -1,
		'fields'         => 'ids',
	) );
	foreach ( $ids as $prod_id ) {
		if ( '' === $layout ) {
			delete_post_meta( $prod_id, '_wp_page_template' );
		} else {
			update_post_meta( $prod_id, '_wp_page_template', $layout );
		}
	}
	wp_safe_redirect( $id ? get_permalink( $id ) : home_url( '/' ) );
	exit;
} );

add_action( 'admin_post_gogh_product_layout', function () {
	$id     = isset( $_GET['id'] ) ? (int) $_GET['id'] : 0;
	$layout = isset( $_GET['layout'] ) ? sanitize_text_field( wp_unslash( $_GET['layout'] ) ) : '';
	if ( ! $id || ! current_user_can( 'edit_post', $id ) ) {
		wp_die( esc_html__( 'You cannot edit this product.', 'gogh-editor' ) );
	}
	check_admin_referer( 'gogh_product_layout_' . $id );
	if ( ! array_key_exists( $layout, gogh_product_layouts() ) ) {
		wp_die( esc_html__( 'Unknown layout.', 'gogh-editor' ) );
	}
	if ( '' === $layout ) {
		delete_post_meta( $id, '_wp_page_template' );
		wp_safe_redirect( get_permalink( $id ) );
	} else {
		update_post_meta( $id, '_wp_page_template', $layout );
		wp_safe_redirect( add_query_arg( 'gogh-edit', '1', get_permalink( $id ) ) );
	}
	exit;
} );

/**
 * Wrapped images: text flows around a floated image's silhouette via
 * shape-outside. KSES must not strip the properties (or the img style) for
 * users below unfiltered_html.
 */
add_filter( 'safe_style_css', function ( $props ) {
	$props[] = 'float';
	$props[] = 'shape-outside';
	$props[] = 'shape-margin';
	$props[] = 'shape-image-threshold';
	return $props;
} );
add_filter( 'wp_kses_allowed_html', function ( $tags, $context ) {
	if ( 'post' === $context && isset( $tags['img'] ) ) {
		$tags['img']['style'] = true;
	}
	return $tags;
}, 10, 2 );

/**
 * Core keys plugin-registered templates by NAME ('gogh//blank-canvas') when
 * it merges them into get_block_templates() results, but wp-includes/
 * block-editor.php reads [0] from that array — on a page using our Blank
 * canvas template the block editor emits warnings and white-screens.
 * Reindexing costs nothing and keeps every caller's expectation of a list.
 */
add_filter( 'get_block_templates', function ( $templates ) {
	return is_array( $templates ) ? array_values( $templates ) : $templates;
} );

/**
 * Pattern previews: core's block-renderer returns markup WITHOUT the
 * per-instance layout CSS (flex/grid/gap rules the style engine generates
 * during render), so grids collapse into a squished huddle in the picker.
 * This route renders a pattern and hands back that CSS alongside the markup.
 */
add_action( 'rest_api_init', function () {
	register_rest_route( 'gogh/v1', '/pattern', array(
		'methods'             => 'GET',
		'permission_callback' => function () {
			return current_user_can( 'edit_posts' );
		},
		'args'                => array( 'slug' => array( 'required' => true, 'type' => 'string' ) ),
		'callback'            => function ( $req ) {
			$pat = WP_Block_Patterns_Registry::get_instance()->get_registered( (string) $req['slug'] );
			if ( ! $pat ) {
				return new WP_Error( 'gogh_no_pattern', __( 'Unknown pattern.', 'gogh-editor' ), array( 'status' => 404 ) );
			}
			$html = do_blocks( (string) $pat['content'] );
			$css  = function_exists( 'wp_style_engine_get_stylesheet_from_context' )
				? wp_style_engine_get_stylesheet_from_context( 'block-supports' )
				: '';
			return array( 'rendered' => $html, 'css' => $css );
		},
	) );
} );

/**
 * Last line of defence for site chrome: gogh's editor UI classes must never
 * appear in STORED template parts or navigation menus. If they do, some
 * DOM-derived markup is being saved by mistake (this once replaced a header
 * with its own rendered DOM, add-page buttons included) — refuse the write
 * loudly instead of corrupting every page on the site.
 */
add_action( 'rest_api_init', function () {
	$guard = function ( $prepared ) {
		$c = is_object( $prepared ) && isset( $prepared->post_content ) ? $prepared->post_content : '';
		foreach ( array( 'gogh-navadd', 'gogh-pendbar', 'gogh-storedrm', 'gogh-convertbtn', 'gogh-selbox', 'data-gogh' ) as $mark ) {
			if ( false !== strpos( $c, $mark ) ) {
				return new WP_Error(
					'gogh_artifact_in_chrome',
					__( 'gogh blocked this save: editor-only markup was about to be stored in site chrome.', 'gogh-editor' ),
					array( 'status' => 400 )
				);
			}
		}
		return $prepared;
	};
	add_filter( 'rest_pre_insert_wp_template_part', $guard );
	add_filter( 'rest_pre_insert_wp_navigation', $guard );
} );

/**
 * Your brand: a small recipe (four colours, two font slugs) stored as a
 * site option and editable over the core settings REST route. Applying it
 * writes user Global Styles through the same path as theme variations.
 */
add_action( 'init', function () {
	register_setting( 'options', 'gogh_brand', array(
		'type'         => 'object',
		'default'      => null,
		'show_in_rest' => array(
			'schema' => array(
				'type'                 => 'object',
				'properties'           => array(
					'colors' => array(
						'type'       => 'object',
						'properties' => array(
							'background' => array( 'type' => 'string' ),
							'text'       => array( 'type' => 'string' ),
							'accent'     => array( 'type' => 'string' ),
							'accent2'    => array( 'type' => 'string' ),
						),
					),
					'fonts'  => array(
						'type'       => 'object',
						'properties' => array(
							'heading' => array( 'type' => 'string' ),
							'body'    => array( 'type' => 'string' ),
						),
					),
				),
				'additionalProperties' => false,
			),
		),
	) );
} );

/**
 * Experience bundles are plain .html uploads — allowed only for users who
 * may already publish arbitrary markup (unfiltered_html), so this grants
 * no capability they don't have.
 */
add_filter( 'upload_mimes', function ( $mimes ) {
	if ( current_user_can( 'unfiltered_html' ) ) {
		$mimes['html'] = 'text/html';
	}
	return $mimes;
} );

/**
 * SPIKE variant B: rebake. On every save — by anyone, including users whose
 * content KSES just filtered — regenerate the baked <style> inside each v3
 * section from its attributes. The plugin authors these bytes server-side,
 * so the saver's capabilities are irrelevant; deactivation keeps the look.
 * ADOPTED as production behaviour (variant B won the matrix): default ON,
 * gogh_rebake_enabled filter remains as the escape hatch.
 */
function gogh_rebake_post_data( $data ) {
	if ( ! apply_filters( 'gogh_rebake_enabled', true ) ) {
		return $data;
	}
	if ( empty( $data['post_content'] ) || false === strpos( $data['post_content'], 'wp:gogh/section' ) ) {
		return $data;
	}
	$content = wp_unslash( $data['post_content'] );
	$blocks  = parse_blocks( $content );
	$changed = false;
	foreach ( $blocks as &$b ) {
		if ( 'gogh/section' !== $b['blockName'] || empty( $b['attrs'] ) ) {
			continue;
		}
		$css = gogh_css_from_attrs( $b['attrs'] );
		if ( '' === $css || false !== strpos( (string) $b['innerHTML'], 'class="gogh-style"' ) ) {
			continue;
		}
		$style = '<style class="gogh-style">' . $css . '</style>';
		foreach ( array( 'innerHTML', 'innerContent' ) as $k ) {
			if ( 'innerContent' === $k ) {
				foreach ( $b['innerContent'] as &$chunk ) {
					if ( is_string( $chunk ) && false !== strpos( $chunk, 'wp-block-gogh-section' ) ) {
						$chunk   = gogh_sweep_css_residue( $chunk );
						$chunk   = preg_replace( '/(<div class="wp-block-gogh-section[^"]*">)/', '$1' . $style, $chunk, 1 );
						$changed = true;
						break;
					}
				}
			} else {
				$b[ $k ] = gogh_sweep_css_residue( (string) $b[ $k ] );
				$b[ $k ] = preg_replace( '/(<div class="wp-block-gogh-section[^"]*">)/', '$1' . $style, $b[ $k ], 1 );
			}
		}
	}
	unset( $b );
	if ( $changed ) {
		$data['post_content'] = wp_slash( serialize_blocks( $blocks ) );
	}
	return $data;
}
add_filter( 'wp_insert_post_data', 'gogh_rebake_post_data', 20 );

/**
 * Front-end editor: enqueue for users who can edit the current page.
 */
add_action( 'wp_enqueue_scripts', function () {
	if ( ! is_singular() ) {
		return;
	}
	$post      = get_post();
	if ( ! $post ) {
		return;
	}
	$has_gogh  = false !== strpos( $post->post_content, 'gogh-section' );
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only view toggle; editor assets are capability-gated below.
	$want_edit = isset( $_GET['gogh-edit'] );
	$can_edit  = current_user_can( 'edit_post', $post->ID );
	// products: the editor belongs on gogh's own layouts only — on Woo's
	// classic template the description hides in tabs and the canvas would
	// fight the buy box (the admin bar's layout menu is the door)
	if ( 'product' === $post->post_type &&
		! in_array( get_page_template_slug( $post ), array( 'gogh-product-story', 'gogh-product-showcase' ), true ) ) {
		return;
	}
	// visitors only need assets on gogh pages; EDITORS get the editor on
	// every singular page — gating on 'gogh-section' in the content is why
	// the floating edit pill never appeared on untouched or empty pages
	if ( ! $has_gogh && ! $want_edit && ! $can_edit ) {
		return;
	}

	// for every visitor: neutralise theme spacing around gogh sections, even
	// on pages whose stored stylesheets predate this rule
	wp_register_style( 'gogh-base', false, array(), '0.99.60-chrome' );
	wp_enqueue_style( 'gogh-base' );
	wp_add_inline_style( 'gogh-base',
		// full-bleed sections use 100vw, which includes the scrollbar — once
		// a vertical scrollbar exists they overflow sideways and the canvas
		// wobbles left-right. Clip horizontal overflow at the root (clip, not
		// hidden: no new scroll container, inner scrollers unaffected).
		'html { overflow-x: clip; }' .
		'.gogh-wrap { margin-block: 0 !important; min-width: 100%; }' .
		'.entry-content:has(> .gogh-wrap) { margin-block: 0 !important; }' .
		// pages saved before this rule shipped: image placeholders must not
		// inherit theme Group padding
		'.gogh-section > .wp-block-group { padding: 0 !important; box-sizing: border-box; }' .
		'.gogh-section > * { box-sizing: border-box; }' .
		// pasted-HTML sections: full bleed with zero vertical margins for
		// every visitor — the theme's block-gap must not band between them
		'.gogh-section-html { box-sizing: border-box !important; width: 100vw !important; max-width: 100vw !important; margin-inline: calc(50% - 50vw) !important; margin-block: 0 !important; }' .
		// the transparent header floats over the first section: absolutely
		// positioned with a soft top scrim so white chrome reads on any hero
		'header.wp-block-template-part:has(> .gogh-header-overlay), header.wp-block-template-part:has(.gogh-header-overlay) { position: absolute; top: var(--wp-admin--admin-bar--height, 0px); left: 0; right: 0; z-index: 40; background: transparent; }' .
		'.gogh-header-overlay { background: linear-gradient(to bottom, rgba(12, 12, 16, 0.38), transparent) !important; }' .
		// WooCommerce block-hooks append cart/account icons after the nav in
		// every header — give them a deliberate seat instead of a random one:
		// nav pushes right, icons tuck in beside it, stacks stay centred
		'.gogh-hrow { align-items: center; gap: 1.1rem; }' .
		'.gogh-hrow > .wp-block-navigation { margin-left: auto; }' .
		'.gogh-hrow > [class*="mini-cart"], .gogh-hrow > [class*="customer-account"] { flex: none; }' .
		'.gogh-hstack > [class*="mini-cart"], .gogh-hstack > [class*="customer-account"] { align-self: center; }' .
		// FAQ + Tabs widgets: quiet, theme-inked styling for the real blocks —
		// the same rules dress the editor preview (the edit page IS the front)
		// the theme's flow blockGap dresses accordion internals like prose —
		// big margins between item, heading and panel (James: "formatting
		// breakage"). The widget owns its rhythm.
		// the widget wrapper is display:flex (it centres SMALL widgets — nav,
		// site title); accordion and tabs are block content and must fill the
		// box, not shrink to their words (the "narrow accordion" report)
		'.gogh-widget > .wp-block-accordion, .gogh-widget > .wp-block-tabs { flex: 1 1 100%; width: 100%; }' .
		'.gogh-widget .wp-block-accordion > *, .gogh-widget .wp-block-accordion-item > *, .gogh-widget .wp-block-tabs > *, .gogh-widget .wp-block-accordion-panel__content > *, .gogh-widget .wp-block-tab-panel > * { margin-block: 0 !important; }' .
		'.gogh-widget .wp-block-accordion-item { border-top: 1px solid color-mix(in srgb, currentColor 16%, transparent); }' .
		'.gogh-widget .wp-block-accordion-item:last-child { border-bottom: 1px solid color-mix(in srgb, currentColor 16%, transparent); }' .
		'.gogh-widget .wp-block-accordion-heading { margin: 0; font-size: 1.02em; }' .
		'.gogh-widget .wp-block-accordion-heading__toggle { display: flex; width: 100%; justify-content: space-between; align-items: center; gap: 1em; padding: 0.9em 0; background: none; border: 0; font: inherit; font-weight: 600; color: inherit; cursor: pointer; text-align: left; }' .
		'.gogh-widget .wp-block-accordion-heading__icon::before { content: "+"; font-size: 1.25em; font-weight: 400; opacity: 0.55; line-height: 1; }' .
		'.gogh-widget .is-open .wp-block-accordion-heading__icon::before, .gogh-widget .wp-block-accordion-item.is-open .wp-block-accordion-heading__icon::before { content: "\2212"; }' .
		'.gogh-widget .wp-block-accordion-panel__content { padding: 0 0 1.1em; opacity: 0.85; }' .
		'.gogh-widget .wp-block-tab-list { display: flex; gap: 0.25em; border-bottom: 1px solid color-mix(in srgb, currentColor 16%, transparent); margin-bottom: 1.2em; }' .
		'.gogh-widget .wp-block-tab-list__tab { padding: 0.7em 1em; background: none; border: 0; border-bottom: 2px solid transparent; margin-bottom: -1px; font: inherit; font-weight: 600; color: inherit; opacity: 0.55; cursor: pointer; }' .
		'.gogh-widget .wp-block-tab-list__tab[aria-selected="true"] { opacity: 1; border-bottom-color: currentColor; }' .
		'.gogh-widget .wp-block-tab-panel { padding-top: 0.2em; }'
	);

	if ( ! current_user_can( 'edit_post', $post->ID ) ) {
		return;
	}

	wp_enqueue_script( 'gogh-editor', plugins_url( 'gogh-editor.js', __FILE__ ), array(), '0.99.60-chrome', true );
	wp_enqueue_style( 'gogh-editor', plugins_url( 'gogh-editor.css', __FILE__ ), array(), '0.99.60-chrome' );

	// WebMCP bridge: the page registers its editing verbs as agent tools.
	// OPT-IN only — add ?gogh-mcp=1 for a demo session (or enable sitewide
	// via the gogh_webmcp_enabled filter). Keeps future WebMCP-speaking
	// agents from discovering publish-capable tools uninvited.
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only opt-in toggle; script is capability-gated above.
	// …and the help bot's show-me bridge rides the same verbs, so the
	// experiments flag loads them too (the bridge itself is origin-checked)
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only labs toggle
	$gogh_exp = isset( $_GET['gogh-test'] ) || ( isset( $_GET['gogh-experiments'] ) && '0' !== $_GET['gogh-experiments'] );
	if ( isset( $_GET['gogh-mcp'] ) || $gogh_exp || apply_filters( 'gogh_webmcp_enabled', false ) ) {
		wp_enqueue_script( 'gogh-webmcp', plugins_url( 'gogh-webmcp.js', __FILE__ ), array( 'gogh-editor' ), '0.99.60-chrome', true );
	}

	// regression suite: /page/?gogh-test (editors only, never saves)
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only toggle enqueuing a test script for capability-checked editors.
	if ( isset( $_GET['gogh-test'] ) ) {
		wp_enqueue_script( 'gogh-tests', plugins_url( 'gogh-tests.js', __FILE__ ), array( 'gogh-editor' ), '0.99.60-chrome', true );
	}

	// products live outside wp/v2, so gogh carries its own save route for
	// them — registered UNDER wp/v2 deliberately: the editor derives the
	// REST root by splitting on 'wp/v2/'
	$rest_base = ( 'page' === $post->post_type ) ? 'pages' : ( 'product' === $post->post_type ? 'gogh-product' : 'posts' );
	wp_localize_script( 'gogh-editor', 'GOGH', array(
		'postId'   => $post->ID,
		'restUrl'  => rest_url( 'wp/v2/' . $rest_base . '/' . $post->ID ),
		'mediaUrl' => rest_url( 'wp/v2/media' ),
		'canUpload' => current_user_can( 'upload_files' ),
		'canExp'   => current_user_can( 'upload_files' ) && current_user_can( 'unfiltered_html' ),
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only labs toggle
		// Make freeform ships on by default; &gogh-experiments=0 is the kill-switch,
		// bare &gogh-experiments opts into future experimental features.
		'canConvert' => apply_filters( 'gogh_convert_enabled', ! isset( $_GET['gogh-experiments'] ) || '0' !== $_GET['gogh-experiments'] ),
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only labs toggle
		'experiments' => isset( $_GET['gogh-test'] ) || ( isset( $_GET['gogh-experiments'] ) && '0' !== $_GET['gogh-experiments'] ),
		// the help bot: gogh's editor embeds it in a small sheet; empty URL
		// (via the filter) removes the ? button entirely
		'helpUrl'  => apply_filters( 'gogh_helper_url', 'https://gogh-helper.jamesmarsland.workers.dev' ),
		'brand'    => get_option( 'gogh_brand', null ) ?: null,
		'activeStyle' => get_option( 'gogh_active_style', '' ),
		'typeScale' => (int) get_option( 'gogh_type_scale', 100 ),
		'hasWoo'   => class_exists( 'WooCommerce' ),
		// block-gated pieces light up the day the block exists (7.1 brings tabs)
		'hasAccordion' => WP_Block_Type_Registry::get_instance()->is_registered( 'core/accordion' ),
		'hasTabs'  => WP_Block_Type_Registry::get_instance()->is_registered( 'core/tabs' ),
		'starters' => array_values( array_map( function ( $m ) {
			return array(
				'slug'        => $m['slug'],
				'name'        => $m['name'],
				'description' => isset( $m['description'] ) ? $m['description'] : '',
				'preview'     => isset( $m['preview'] ) ? $m['preview'] : null,
				'pages'       => array_map( function ( $pg ) {
					return array( 'slug' => $pg['slug'], 'title' => $pg['title'] );
				}, $m['pages'] ),
			);
		}, gogh_starters() ) ),
		'pageTemplate'  => get_page_template_slug( $post ) ?: '',
		'pageTemplates' => (function () use ( $post ) {
			$out = array();
			// includes gogh's registered Blank canvas (as 'blank-canvas') on WP 6.7+
			foreach ( (array) wp_get_theme()->get_page_templates( $post ) as $slug => $title ) {
				$out[] = array( 'slug' => (string) $slug, 'title' => (string) $title );
			}
			return $out;
		})(),
		'modified' => get_post_modified_time( 'Y-m-d\TH:i:s', true, $post ),
		'theme'    => get_stylesheet(),
		'themeName' => wp_get_theme()->get( 'Name' ),
		'gsId'     => ( class_exists( 'WP_Theme_JSON_Resolver' ) && current_user_can( 'edit_theme_options' ) )
			? WP_Theme_JSON_Resolver::get_user_global_styles_post_id() : 0,
		'palette'  => array_values( array_map(
			function ( $c ) { return array( 'slug' => $c['slug'] ); },
			(array) ( wp_get_global_settings( array( 'color', 'palette' ) )['theme'] ?? array() )
		) ),
		'nonce'    => wp_create_nonce( 'wp_rest' ),
	) );
} );

/**
 * Live-preview renderer: the core block-renderer returns bare markup with
 * none of the per-instance layout CSS (nav flex rules, container gaps), so
 * header/footer previews looked broken. This renders markup the way a real
 * page does and returns the generated styles + the block stylesheets the
 * markup needs.
 */
add_action( 'rest_api_init', function () {
	register_rest_route( 'gogh/v1', '/render', array(
		'methods'             => 'POST',
		'permission_callback' => function () {
			return current_user_can( 'edit_posts' );
		},
		'callback'            => function ( $req ) {
			$content = (string) $req->get_param( 'content' );
			$html    = do_blocks( $content );
			$css     = function_exists( 'wp_style_engine_get_stylesheet_from_context' )
				? (string) wp_style_engine_get_stylesheet_from_context( 'block-supports' )
				: '';
			$hrefs = array();
			$walk  = function ( $blocks ) use ( &$walk, &$hrefs ) {
				foreach ( $blocks as $b ) {
					if ( ! empty( $b['blockName'] ) ) {
						$bt = WP_Block_Type_Registry::get_instance()->get_registered( $b['blockName'] );
						if ( $bt ) {
							foreach ( (array) $bt->style_handles as $h ) {
								if ( $h && wp_style_is( $h, 'registered' ) ) {
									$obj = wp_styles()->registered[ $h ];
									if ( ! empty( $obj->src ) ) {
										$src = ( 0 === strpos( $obj->src, 'http' ) ) ? $obj->src : site_url( $obj->src );
										$hrefs[ $h ] = add_query_arg( 'ver', $obj->ver ? $obj->ver : get_bloginfo( 'version' ), $src );
									}
								}
							}
						}
					}
					if ( ! empty( $b['innerBlocks'] ) ) {
						$walk( $b['innerBlocks'] );
					}
				}
			};
			$walk( parse_blocks( $content ) );
			return array(
				'html'   => $html,
				'css'    => $css,
				'styles' => array_values( $hrefs ),
			);
		},
	) );
} );

/**
 * Editor contexts (post editor, site editor, pattern previews): a gogh
 * section's grid uses cqw units against the .gogh-wrap container. In
 * shrink-to-fit preview wrappers, inline-size containment collapses the wrap
 * to width 0 — every saved section needs the same width floor there.
 */
add_action( 'enqueue_block_assets', function () {
	if ( ! is_admin() ) {
		return;
	}
	wp_register_style( 'gogh-editor-base', false, array(), '0.99.60-chrome' );
	wp_enqueue_style( 'gogh-editor-base' );
	wp_add_inline_style( 'gogh-editor-base',
		'.gogh-wrap { min-width: 100%; margin-block: 0 !important; }' .
		'.gogh-section > .wp-block-group { padding: 0 !important; box-sizing: border-box; }' .
		'.gogh-section > * { box-sizing: border-box; }'
	);
} );

/**
 * Admin-bar entry point: "Edit with gogh" on any front-end page the user can
 * edit. On a page with no gogh content yet, the editor bootstraps a section.
 */
add_action( 'admin_bar_menu', function ( $bar ) {
	if ( is_admin() || ! is_singular() ) {
		return;
	}
	$post = get_post();
	if ( ! $post || ! current_user_can( 'edit_post', $post->ID ) ) {
		return;
	}
	// while editing, the same landmark becomes the one obvious way OUT
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only mode check
	$editing = isset( $_GET['gogh-edit'] );
	$bar->add_node( array(
		'id'    => 'gogh-edit',
		'title' => $editing ? '🎨 Exit gogh editor' : '🎨 Edit with gogh',
		'href'  => $editing
			? get_permalink( $post )
			: add_query_arg( 'gogh-edit', '1', get_permalink( $post ) ),
	) );
}, 90 );

/**
 * v1 posture: the front-end admin bar shows ONE way to edit — gogh. The
 * native entry points (Site Editor, Edit Page, +New, comments) return with
 * the experiments flag for the curious.
 */
add_action( 'admin_bar_menu', function ( $bar ) {
	if ( is_admin() ) {
		return;
	}
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only mode check
	if ( isset( $_GET['gogh-experiments'] ) || isset( $_GET['gogh-test'] ) ) {
		return;
	}
	foreach ( array( 'site-editor', 'edit-site', 'customize', 'comments', 'new-content', 'edit' ) as $id ) {
		$bar->remove_node( $id );
	}
	// products: a tiny layout menu — pick one of a few fixed layouts,
	// never edit a template
	if ( is_singular( 'product' ) && function_exists( 'gogh_product_layouts' ) ) {
		$pid = get_queried_object_id();
		if ( $pid && current_user_can( 'edit_post', $pid ) ) {
			$current = get_page_template_slug( $pid );
			$layouts = gogh_product_layouts();
			if ( ! isset( $layouts[ $current ] ) ) {
				$current = '';
			}
			$bar->add_node( array(
				'id'    => 'gogh-product-layout',
				'title' => '🎨 Product layout',
			) );
			foreach ( $layouts as $slug => $label ) {
				$bar->add_node( array(
					'id'     => 'gogh-product-layout-' . ( $slug ? $slug : 'classic' ),
					'parent' => 'gogh-product-layout',
					'title'  => ( $slug === $current ? '✓ ' : '' ) . $label,
					'href'   => wp_nonce_url( admin_url( 'admin-post.php?action=gogh_product_layout&id=' . $pid . '&layout=' . rawurlencode( $slug ) ), 'gogh_product_layout_' . $pid ),
				) );
			}
			// one more click stamps the catalogue — individual products can
			// still be changed afterwards, one at a time
			$current_label = preg_replace( '/\s+—.*$/u', '', $layouts[ $current ] );
			$bar->add_node( array(
				'id'     => 'gogh-product-layout-all',
				'parent' => 'gogh-product-layout',
				'title'  => sprintf( __( 'Apply “%s” to all products', 'gogh-editor' ), $current_label ),
				'href'   => wp_nonce_url( admin_url( 'admin-post.php?action=gogh_product_layout_all&id=' . $pid ), 'gogh_product_layout_all' ),
			) );
		}
	}
	// one thing beginners DO need from the old menu: a new page — and it
	// goes straight into gogh
	if ( current_user_can( 'publish_pages' ) ) {
		$bar->add_node( array(
			'id'    => 'gogh-new-page',
			'title' => '+ New page',
			'href'  => wp_nonce_url( admin_url( 'admin-post.php?action=gogh_new_page' ), 'gogh_new_page' ),
		) );
		// keep "+ New page" BEFORE the edit/exit landmark: re-adding a node
		// sends it to the end of the row
		$edit_node = $bar->get_node( 'gogh-edit' );
		if ( $edit_node ) {
			$bar->remove_node( 'gogh-edit' );
			$bar->add_node( (array) $edit_node );
		}
	}
}, 999 );

/**
 * EXPERIMENT (&gogh-experiments): "+ New → Page" from the front-end admin
 * bar creates the page and lands straight in gogh, not the block editor.
 */
add_action( 'admin_bar_menu', function ( $bar ) {
	if ( is_admin() ) {
		return;
	}
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only mode check
	if ( ! ( isset( $_GET['gogh-experiments'] ) || isset( $_GET['gogh-test'] ) ) ) {
		return;
	}
	$node = $bar->get_node( 'new-page' );
	if ( $node ) {
		$node->href = wp_nonce_url( admin_url( 'admin-post.php?action=gogh_new_page' ), 'gogh_new_page' );
		$bar->add_node( (array) $node );
	}
}, 1000 );
add_action( 'admin_post_gogh_new_page', function () {
	if ( ! current_user_can( 'publish_pages' ) ) {
		wp_die( esc_html__( 'You cannot create pages on this site.', 'gogh-editor' ) );
	}
	check_admin_referer( 'gogh_new_page' );
	$id = wp_insert_post( array(
		'post_type'   => 'page',
		'post_status' => 'publish',
		'post_title'  => __( 'Untitled page', 'gogh-editor' ),
	) );
	wp_safe_redirect( add_query_arg( 'gogh-edit', '1', get_permalink( $id ) ) );
	exit;
} );

/**
 * Backend parity: inject the page's own generated gogh CSS into the block
 * editor iframe so the editor canvas renders the section like the front end.
 */
add_filter( 'block_editor_settings_all', function ( $settings, $context ) {
	$post = isset( $context->post ) ? $context->post : null;
	if ( ! $post || false === strpos( $post->post_content, 'gogh-section' ) ) {
		return $settings;
	}
	if ( ! preg_match_all( '/<style class="gogh-style">(.*?)<\/style>/s', $post->post_content, $m ) ) {
		return $settings;
	}

	$css = implode( "\n", $m[1] );

	// Editor-only adjustments:
	// 1. The group block's inner-blocks wrappers would break the grid —
	//    promote grandchildren into the grid with display:contents.
	// 2. Hide the leading Custom HTML block that carries the style + model.
	$css .= "\n"
		. '.gogh-section > .block-editor-inner-blocks,'
		. '.gogh-section > div:not([class]),'
		// empty groups (gogh boxes/shapes) get an extra CLASS-LESS wrapper from
		// the editor — promote it too, or the anonymous div becomes the grid
		// item: auto-placed, zero-height, shape invisible
		. '.gogh-section .block-editor-block-list__layout > div:not([class]),'
		. '.gogh-section .block-editor-inner-blocks > .block-editor-block-list__layout { display: contents; }' . "\n"
		. '.is-root-container > [data-type="core/html"]:first-child { display: none; }' . "\n"
		// gogh/section blocks span the full editor canvas, like the front end
		. '.editor-styles-wrapper [data-type="gogh/section"],'
		. '.editor-styles-wrapper .wp-block:has(> .wp-block-gogh-section) {'
		. ' max-width: none !important; width: auto;'
		// kill the editor's block-gap margins so sections sit flush, like the front end
		. ' margin-block: 0 !important;'
		. ' margin-left: calc(-1 * var(--wp--style--root--padding-left, 0px)) !important;'
		. ' margin-right: calc(-1 * var(--wp--style--root--padding-right, 0px)) !important; }' . "\n"
		. '.gogh-wrap { margin-block: 0 !important; }' . "\n"
		// empty image/decoration groups: suppress Gutenberg's layout variation
		// picker and appender so the div renders with its gogh background
		. '.gogh-section .block-editor-block-variation-picker,'
		. '.gogh-section .wp-block-group__placeholder > .components-placeholder,'
		. '.gogh-section .block-list-appender { display: none !important; }';

	$settings['styles'][] = array( 'css' => $css );
	return $settings;
}, 10, 2 );
