<?php
/**
 * Plugin Name: Gogh Editor
 * Description: A freeform canvas for WordPress — drag anything anywhere on your live page; Gogh publishes it back as clean, responsive core blocks that keep working even if the plugin is deactivated.
 * Version: 0.86.3
 * Author: Jamie Marsland
 * Author URI: https://pootlepress.com
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Requires at least: 6.5
 * Requires PHP: 7.4
 * Text Domain: gogh-editor
 */

defined( 'ABSPATH' ) || exit;

/**
 * gogh/section — a first-class block. STATIC save (no render_callback), so
 * pages keep rendering identically if the plugin is ever deactivated.
 */
add_action( 'init', function () {
	wp_register_script(
		'gogh-block',
		plugins_url( 'gogh-block.js', __FILE__ ),
		array( 'wp-blocks', 'wp-element', 'wp-block-editor' ),
		'0.86.3-chrome',
		true
	);
	register_block_type( 'gogh/section', array(
		'editor_script'   => 'gogh-block',
		// SPIKE (attrs-as-truth): v3 sections store { model, cssT } as block
		// attributes and derive presentation here. Legacy (v2) sections carry
		// no attributes and pass through verbatim — fully static, unchanged.
		'render_callback' => 'gogh_render_section',
	) );
} );

/**
 * SPIKE: emit a v3 section. PHP does scoping + emission ONLY — the layout
 * engine stays in the editor; cssT arrives fully compiled with a GOGHSCOPE
 * placeholder.
 *
 * SECURITY: block attributes are writable by users WITHOUT unfiltered_html
 * (KSES does not police attribute JSON), so everything emitted from them is
 * sanitized here: the scope is slug-cast and the CSS may not contain the
 * characters that could open an element or comment. Without this, cssT would
 * be a stored-XSS bypass around KSES.
 */
function gogh_css_from_attrs( $attrs ) {
	if ( empty( $attrs['cssT'] ) || empty( $attrs['scope'] ) ) {
		return '';
	}
	$scope = preg_replace( '/[^a-z0-9-]/', '', (string) $attrs['scope'] );
	if ( '' === $scope ) {
		return '';
	}
	$css = str_replace( 'GOGHSCOPE', $scope, (string) $attrs['cssT'] );
	// CSS never needs these characters; their absence makes markup injection impossible
	return str_replace( array( '<', '>', '\\' ), '', $css );
}

/**
 * When KSES strips a baked <style> TAG it leaves the CSS behind as loose
 * text. Our stylesheets all open with a sentinel comment and never contain
 * '<', so the residue is precisely delimited and safe to sweep.
 */
function gogh_sweep_css_residue( $html ) {
	return preg_replace( '/\/\* generated by gogh \*\/[^<]*/', '', $html );
}

function gogh_render_section( $attrs, $content ) {
	$attrs = is_array( $attrs ) ? $attrs : array();
	$css   = gogh_css_from_attrs( $attrs );
	if ( '' === $css ) {
		return $content; // legacy v2: static markup is already complete
	}
	if ( false === strpos( $content, 'class="gogh-style"' ) ) {
		$content = gogh_sweep_css_residue( $content );
		$style   = '<style class="gogh-style">' . $css . '</style>';
		$out     = preg_replace( '/(<div class="wp-block-gogh-section[^"]*">)/', '$1' . $style, $content, 1, $n );
		$content = $n ? $out : $style . $content;
	}
	return gogh_inject_experiences( $attrs, $content );
}

/**
 * Experiences: stored markup carries only a plain link (kses-safe, and the
 * plugin-off fallback). At render time it becomes a sandboxed iframe. The
 * src is NEVER taken from attributes — only the attachment ID is, and the
 * URL is resolved server-side after checking the attachment really is an
 * uploaded text/html file (uploads of which are capability-gated below).
 * allow-scripts WITHOUT allow-same-origin = opaque origin: the uploaded
 * code cannot read cookies or reach the embedding page.
 */
function gogh_inject_experiences( $attrs, $content ) {
	$els = isset( $attrs['model']['elements'] ) && is_array( $attrs['model']['elements'] )
		? $attrs['model']['elements'] : array();
	foreach ( $els as $i => $e ) {
		if ( empty( $e['type'] ) || 'exp' !== $e['type'] || empty( $e['expId'] ) ) {
			continue;
		}
		$id = intval( $e['expId'] );
		if ( $id <= 0 || 'text/html' !== get_post_mime_type( $id ) ) {
			continue;
		}
		$src = wp_get_attachment_url( $id );
		if ( ! $src ) {
			continue;
		}
		$iframe  = '<iframe src="' . esc_url( $src ) . '" sandbox="allow-scripts" title="Interactive experience" loading="lazy" style="width:100%;height:100%;border:0;display:block"></iframe>';
		// the class list gains render-time extras (layout support), so match
		// by our two authored classes rather than the exact attribute value
		$content = preg_replace_callback(
			'/(<div class="[^"]*\bgogh-el-' . ( $i + 1 ) . '\b[^"]*\bgogh-exp\b[^"]*">).*?<\/div>/s',
			function ( $m ) use ( $iframe ) {
				return $m[1] . $iframe . '</div>';
			},
			$content,
			1
		);
	}
	return $content;
}

/**
 * Experience bundles are plain .html uploads — allowed only for users who
 * may already publish arbitrary markup (unfiltered_html), so this grants
 * no capability they don't have.
 */
add_filter( 'upload_mimes', function ( $mimes ) {
	if ( current_user_can( 'unfiltered_html' ) ) {
		$mimes['html'] = 'text/html';
	}
	return $mimes;
} );

/**
 * SPIKE variant B: rebake. On every save — by anyone, including users whose
 * content KSES just filtered — regenerate the baked <style> inside each v3
 * section from its attributes. The plugin authors these bytes server-side,
 * so the saver's capabilities are irrelevant; deactivation keeps the look.
 * ADOPTED as production behaviour (variant B won the matrix): default ON,
 * gogh_rebake_enabled filter remains as the escape hatch.
 */
function gogh_rebake_post_data( $data ) {
	if ( ! apply_filters( 'gogh_rebake_enabled', true ) ) {
		return $data;
	}
	if ( empty( $data['post_content'] ) || false === strpos( $data['post_content'], 'wp:gogh/section' ) ) {
		return $data;
	}
	$content = wp_unslash( $data['post_content'] );
	$blocks  = parse_blocks( $content );
	$changed = false;
	foreach ( $blocks as &$b ) {
		if ( 'gogh/section' !== $b['blockName'] || empty( $b['attrs'] ) ) {
			continue;
		}
		$css = gogh_css_from_attrs( $b['attrs'] );
		if ( '' === $css || false !== strpos( (string) $b['innerHTML'], 'class="gogh-style"' ) ) {
			continue;
		}
		$style = '<style class="gogh-style">' . $css . '</style>';
		foreach ( array( 'innerHTML', 'innerContent' ) as $k ) {
			if ( 'innerContent' === $k ) {
				foreach ( $b['innerContent'] as &$chunk ) {
					if ( is_string( $chunk ) && false !== strpos( $chunk, 'wp-block-gogh-section' ) ) {
						$chunk   = gogh_sweep_css_residue( $chunk );
						$chunk   = preg_replace( '/(<div class="wp-block-gogh-section[^"]*">)/', '$1' . $style, $chunk, 1 );
						$changed = true;
						break;
					}
				}
			} else {
				$b[ $k ] = gogh_sweep_css_residue( (string) $b[ $k ] );
				$b[ $k ] = preg_replace( '/(<div class="wp-block-gogh-section[^"]*">)/', '$1' . $style, $b[ $k ], 1 );
			}
		}
	}
	unset( $b );
	if ( $changed ) {
		$data['post_content'] = wp_slash( serialize_blocks( $blocks ) );
	}
	return $data;
}
add_filter( 'wp_insert_post_data', 'gogh_rebake_post_data', 20 );

/**
 * Front-end editor: enqueue for users who can edit the current page.
 */
add_action( 'wp_enqueue_scripts', function () {
	if ( ! is_singular() ) {
		return;
	}
	$post      = get_post();
	$has_gogh  = $post && false !== strpos( $post->post_content, 'gogh-section' );
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only view toggle; editor assets are capability-gated below.
	$want_edit = isset( $_GET['gogh-edit'] );
	if ( ! $post || ( ! $has_gogh && ! $want_edit ) ) {
		return;
	}

	// for every visitor: neutralise theme spacing around gogh sections, even
	// on pages whose stored stylesheets predate this rule
	wp_register_style( 'gogh-base', false, array(), '0.86.3-chrome' );
	wp_enqueue_style( 'gogh-base' );
	wp_add_inline_style( 'gogh-base',
		// full-bleed sections use 100vw, which includes the scrollbar — once
		// a vertical scrollbar exists they overflow sideways and the canvas
		// wobbles left-right. Clip horizontal overflow at the root (clip, not
		// hidden: no new scroll container, inner scrollers unaffected).
		'html { overflow-x: clip; }' .
		'.gogh-wrap { margin-block: 0 !important; min-width: 100%; }' .
		'.entry-content:has(> .gogh-wrap) { margin-block: 0 !important; }' .
		// pages saved before this rule shipped: image placeholders must not
		// inherit theme Group padding
		'.gogh-section > .wp-block-group { padding: 0 !important; box-sizing: border-box; }' .
		'.gogh-section > * { box-sizing: border-box; }' .
		// pasted-HTML sections: full bleed with zero vertical margins for
		// every visitor — the theme's block-gap must not band between them
		'.gogh-section-html { box-sizing: border-box !important; width: 100vw !important; max-width: 100vw !important; margin-inline: calc(50% - 50vw) !important; margin-block: 0 !important; }'
	);

	if ( ! current_user_can( 'edit_post', $post->ID ) ) {
		return;
	}

	wp_enqueue_script( 'gogh-editor', plugins_url( 'gogh-editor.js', __FILE__ ), array(), '0.86.3-chrome', true );
	wp_enqueue_style( 'gogh-editor', plugins_url( 'gogh-editor.css', __FILE__ ), array(), '0.86.3-chrome' );

	// WebMCP bridge: the page registers its editing verbs as agent tools.
	// OPT-IN only — add ?gogh-mcp=1 for a demo session (or enable sitewide
	// via the gogh_webmcp_enabled filter). Keeps future WebMCP-speaking
	// agents from discovering publish-capable tools uninvited.
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only opt-in toggle; script is capability-gated above.
	if ( isset( $_GET['gogh-mcp'] ) || isset( $_GET['gogh-test'] ) || apply_filters( 'gogh_webmcp_enabled', false ) ) {
		wp_enqueue_script( 'gogh-webmcp', plugins_url( 'gogh-webmcp.js', __FILE__ ), array( 'gogh-editor' ), '0.86.3-chrome', true );
	}

	// regression suite: /page/?gogh-test (editors only, never saves)
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only toggle enqueuing a test script for capability-checked editors.
	if ( isset( $_GET['gogh-test'] ) ) {
		wp_enqueue_script( 'gogh-tests', plugins_url( 'gogh-tests.js', __FILE__ ), array( 'gogh-editor' ), '0.86.3-chrome', true );
	}

	$rest_base = ( 'page' === $post->post_type ) ? 'pages' : 'posts';
	wp_localize_script( 'gogh-editor', 'GOGH', array(
		'postId'   => $post->ID,
		'restUrl'  => rest_url( 'wp/v2/' . $rest_base . '/' . $post->ID ),
		'mediaUrl' => rest_url( 'wp/v2/media' ),
		'canUpload' => current_user_can( 'upload_files' ),
		'canExp'   => current_user_can( 'upload_files' ) && current_user_can( 'unfiltered_html' ),
		'modified' => get_post_modified_time( 'Y-m-d\TH:i:s', true, $post ),
		'theme'    => get_stylesheet(),
		'themeName' => wp_get_theme()->get( 'Name' ),
		'gsId'     => ( class_exists( 'WP_Theme_JSON_Resolver' ) && current_user_can( 'edit_theme_options' ) )
			? WP_Theme_JSON_Resolver::get_user_global_styles_post_id() : 0,
		'palette'  => array_values( array_map(
			function ( $c ) { return array( 'slug' => $c['slug'] ); },
			(array) ( wp_get_global_settings( array( 'color', 'palette' ) )['theme'] ?? array() )
		) ),
		'nonce'    => wp_create_nonce( 'wp_rest' ),
	) );
} );

/**
 * Live-preview renderer: the core block-renderer returns bare markup with
 * none of the per-instance layout CSS (nav flex rules, container gaps), so
 * header/footer previews looked broken. This renders markup the way a real
 * page does and returns the generated styles + the block stylesheets the
 * markup needs.
 */
add_action( 'rest_api_init', function () {
	register_rest_route( 'gogh/v1', '/render', array(
		'methods'             => 'POST',
		'permission_callback' => function () {
			return current_user_can( 'edit_posts' );
		},
		'callback'            => function ( $req ) {
			$content = (string) $req->get_param( 'content' );
			$html    = do_blocks( $content );
			$css     = function_exists( 'wp_style_engine_get_stylesheet_from_context' )
				? (string) wp_style_engine_get_stylesheet_from_context( 'block-supports' )
				: '';
			$hrefs = array();
			$walk  = function ( $blocks ) use ( &$walk, &$hrefs ) {
				foreach ( $blocks as $b ) {
					if ( ! empty( $b['blockName'] ) ) {
						$bt = WP_Block_Type_Registry::get_instance()->get_registered( $b['blockName'] );
						if ( $bt ) {
							foreach ( (array) $bt->style_handles as $h ) {
								if ( $h && wp_style_is( $h, 'registered' ) ) {
									$obj = wp_styles()->registered[ $h ];
									if ( ! empty( $obj->src ) ) {
										$src = ( 0 === strpos( $obj->src, 'http' ) ) ? $obj->src : site_url( $obj->src );
										$hrefs[ $h ] = add_query_arg( 'ver', $obj->ver ? $obj->ver : get_bloginfo( 'version' ), $src );
									}
								}
							}
						}
					}
					if ( ! empty( $b['innerBlocks'] ) ) {
						$walk( $b['innerBlocks'] );
					}
				}
			};
			$walk( parse_blocks( $content ) );
			return array(
				'html'   => $html,
				'css'    => $css,
				'styles' => array_values( $hrefs ),
			);
		},
	) );
} );

/**
 * Editor contexts (post editor, site editor, pattern previews): a gogh
 * section's grid uses cqw units against the .gogh-wrap container. In
 * shrink-to-fit preview wrappers, inline-size containment collapses the wrap
 * to width 0 — every saved section needs the same width floor there.
 */
add_action( 'enqueue_block_assets', function () {
	if ( ! is_admin() ) {
		return;
	}
	wp_register_style( 'gogh-editor-base', false, array(), '0.86.3-chrome' );
	wp_enqueue_style( 'gogh-editor-base' );
	wp_add_inline_style( 'gogh-editor-base',
		'.gogh-wrap { min-width: 100%; margin-block: 0 !important; }' .
		'.gogh-section > .wp-block-group { padding: 0 !important; box-sizing: border-box; }' .
		'.gogh-section > * { box-sizing: border-box; }'
	);
} );

/**
 * Admin-bar entry point: "Edit with gogh" on any front-end page the user can
 * edit. On a page with no gogh content yet, the editor bootstraps a section.
 */
add_action( 'admin_bar_menu', function ( $bar ) {
	if ( is_admin() || ! is_singular() ) {
		return;
	}
	$post = get_post();
	if ( ! $post || ! current_user_can( 'edit_post', $post->ID ) ) {
		return;
	}
	$bar->add_node( array(
		'id'    => 'gogh-edit',
		'title' => '🎨 Edit with gogh',
		'href'  => add_query_arg( 'gogh-edit', '1', get_permalink( $post ) ),
	) );
}, 90 );

/**
 * Backend parity: inject the page's own generated gogh CSS into the block
 * editor iframe so the editor canvas renders the section like the front end.
 */
add_filter( 'block_editor_settings_all', function ( $settings, $context ) {
	$post = isset( $context->post ) ? $context->post : null;
	if ( ! $post || false === strpos( $post->post_content, 'gogh-section' ) ) {
		return $settings;
	}
	if ( ! preg_match_all( '/<style class="gogh-style">(.*?)<\/style>/s', $post->post_content, $m ) ) {
		return $settings;
	}

	$css = implode( "\n", $m[1] );

	// Editor-only adjustments:
	// 1. The group block's inner-blocks wrappers would break the grid —
	//    promote grandchildren into the grid with display:contents.
	// 2. Hide the leading Custom HTML block that carries the style + model.
	$css .= "\n"
		. '.gogh-section > .block-editor-inner-blocks,'
		. '.gogh-section > div:not([class]),'
		// empty groups (gogh boxes/shapes) get an extra CLASS-LESS wrapper from
		// the editor — promote it too, or the anonymous div becomes the grid
		// item: auto-placed, zero-height, shape invisible
		. '.gogh-section .block-editor-block-list__layout > div:not([class]),'
		. '.gogh-section .block-editor-inner-blocks > .block-editor-block-list__layout { display: contents; }' . "\n"
		. '.is-root-container > [data-type="core/html"]:first-child { display: none; }' . "\n"
		// gogh/section blocks span the full editor canvas, like the front end
		. '.editor-styles-wrapper [data-type="gogh/section"],'
		. '.editor-styles-wrapper .wp-block:has(> .wp-block-gogh-section) {'
		. ' max-width: none !important; width: auto;'
		// kill the editor's block-gap margins so sections sit flush, like the front end
		. ' margin-block: 0 !important;'
		. ' margin-left: calc(-1 * var(--wp--style--root--padding-left, 0px)) !important;'
		. ' margin-right: calc(-1 * var(--wp--style--root--padding-right, 0px)) !important; }' . "\n"
		. '.gogh-wrap { margin-block: 0 !important; }' . "\n"
		// empty image/decoration groups: suppress Gutenberg's layout variation
		// picker and appender so the div renders with its gogh background
		. '.gogh-section .block-editor-block-variation-picker,'
		. '.gogh-section .wp-block-group__placeholder > .components-placeholder,'
		. '.gogh-section .block-list-appender { display: none !important; }';

	$settings['styles'][] = array( 'css' => $css );
	return $settings;
}, 10, 2 );
